[CmdletBinding()]
param(
    [string]$ConfigPath,
    [ValidateRange(1, 5)][int]$Samples = 2,
    [ValidateRange(100000, 100000000)][long]$TestBytes = 5000000,
    [string]$TestUrl,
    [switch]$SkipBenchmark,
    [string]$PolicyJsonPath,
    [switch]$AsJson
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
if (-not $ConfigPath) {
    $localConfig = Join-Path $projectRoot 'config\routepilot.local.json'
    $ConfigPath = if (Test-Path -LiteralPath $localConfig -PathType Leaf) {
        $localConfig
    } else {
        Join-Path $projectRoot 'config\presets\ai-media.json'
    }
}
if (-not $TestUrl) { $TestUrl = "https://speed.cloudflare.com/__down?bytes=$TestBytes" }
if (-not (Test-Path -LiteralPath $ConfigPath -PathType Leaf)) { throw "Configuration not found: $ConfigPath" }

function Test-LocalPort {
    param([Parameter(Mandatory)][string]$HostName, [Parameter(Mandatory)][int]$Port)
    $tcp = New-Object Net.Sockets.TcpClient
    try {
        $pending = $tcp.BeginConnect($HostName, $Port, $null, $null)
        if (-not $pending.AsyncWaitHandle.WaitOne(700)) { return $false }
        $tcp.EndConnect($pending)
        return $true
    } catch {
        return $false
    } finally {
        $tcp.Close()
    }
}

function Get-Median {
    param([double[]]$Values)
    if (-not $Values -or $Values.Count -eq 0) { return $null }
    $sorted = @($Values | Sort-Object)
    $middle = [int][Math]::Floor($sorted.Count / 2)
    if ($sorted.Count % 2 -eq 1) { return [double]$sorted[$middle] }
    return ([double]$sorted[$middle - 1] + [double]$sorted[$middle]) / 2
}

function Get-EdgePolicyState {
    param([string]$FixturePath)
    $rawPolicy = $null
    try {
        if ($FixturePath) {
            if (Test-Path -LiteralPath $FixturePath -PathType Leaf) {
                $rawPolicy = Get-Content -Raw -LiteralPath $FixturePath
            }
        } else {
            $rawPolicy = [string](Get-ItemPropertyValue -Path 'HKCU:\Software\Policies\Microsoft\Edge' -Name 'ProxySettings')
        }
    } catch { }

    if ([string]::IsNullOrWhiteSpace([string]$rawPolicy)) {
        return [pscustomobject]@{ State = 'Disabled'; Active = $false; Detail = 'No Edge PAC policy was detected.' }
    }

    try {
        $policy = $rawPolicy | ConvertFrom-Json
        if ($policy.ProxyMode -ne 'pac_script') {
            return [pscustomobject]@{ State = 'OtherPolicy'; Active = $false; Detail = 'Edge uses a different proxy policy.' }
        }
        $prefix = 'data:application/x-ns-proxy-autoconfig;base64,'
        $pacUrl = [string]$policy.ProxyPacUrl
        if (-not $pacUrl.StartsWith($prefix)) {
            return [pscustomobject]@{ State = 'OtherPolicy'; Active = $false; Detail = 'Edge uses a non-embedded PAC policy.' }
        }
        $pacBytes = [Convert]::FromBase64String($pacUrl.Substring($prefix.Length))
        $pacText = [Text.Encoding]::UTF8.GetString($pacBytes)
        $active = $policy.ProxyPacMandatory -eq $true -and $pacText.Contains('Generated by RoutePilot')
        return [pscustomobject]@{
            State = if ($active) { 'Active' } else { 'OtherPolicy' }
            Active = $active
            Detail = if ($active) { 'The embedded RoutePilot PAC is active.' } else { 'An Edge PAC exists, but it was not generated by RoutePilot.' }
        }
    } catch {
        return [pscustomobject]@{ State = 'Invalid'; Active = $false; Detail = 'The Edge proxy policy could not be parsed.' }
    }
}

function Measure-ProxyDownload {
    param(
        [Parameter(Mandatory)][string]$HostName,
        [Parameter(Mandatory)][int]$Port,
        [Parameter(Mandatory)][string]$Url,
        [Parameter(Mandatory)][int]$Count
    )
    $curl = Get-Command curl.exe -ErrorAction SilentlyContinue
    if (-not $curl) {
        return [pscustomobject]@{ MedianMbps = $null; Values = @(); Error = 'curl.exe is not available.' }
    }

    $values = @()
    $lastError = $null
    for ($index = 0; $index -lt $Count; $index++) {
        try {
            $proxyUrl = "http://${HostName}:$Port"
            $raw = (& $curl.Source -4 --silent --show-error --fail --location --connect-timeout 10 --max-time 45 --proxy $proxyUrl --output NUL --write-out '%{speed_download}' $Url 2>$null | Out-String).Trim()
            if ($LASTEXITCODE -ne 0) { throw "curl exited with code $LASTEXITCODE" }
            $bytesPerSecond = 0.0
            $parsed = [double]::TryParse($raw, [Globalization.NumberStyles]::Float, [Globalization.CultureInfo]::InvariantCulture, [ref]$bytesPerSecond)
            if (-not $parsed -or $bytesPerSecond -le 0) { throw "Unexpected speed value: $raw" }
            $values += [Math]::Round(($bytesPerSecond * 8) / 1000000, 2)
        } catch {
            $lastError = $_.Exception.Message
        }
    }
    $median = Get-Median -Values ([double[]]$values)
    return [pscustomobject]@{
        MedianMbps = if ($null -eq $median) { $null } else { [Math]::Round($median, 2) }
        Values = @($values)
        Error = if ($values.Count -gt 0) { $null } else { $lastError }
    }
}

$config = Get-Content -Raw -LiteralPath $ConfigPath | ConvertFrom-Json
$primaryHost = ([string]$config.primaryProxy.host).Trim().ToLowerInvariant()
$bulkHost = ([string]$config.bulkProxy.host).Trim().ToLowerInvariant()
if ($primaryHost -notin @('127.0.0.1', 'localhost') -or $bulkHost -notin @('127.0.0.1', 'localhost')) {
    throw 'The monitor only benchmarks loopback HTTP proxies.'
}
$primaryPort = [int]$config.primaryProxy.port
$bulkPort = [int]$config.bulkProxy.port
$primaryReady = Test-LocalPort -HostName $primaryHost -Port $primaryPort
$bulkReady = Test-LocalPort -HostName $bulkHost -Port $bulkPort
$policyState = Get-EdgePolicyState -FixturePath $PolicyJsonPath

$primaryMeasurement = [pscustomobject]@{ MedianMbps = $null; Values = @(); Error = $null }
$bulkMeasurement = [pscustomobject]@{ MedianMbps = $null; Values = @(); Error = $null }
if (-not $SkipBenchmark) {
    if ($primaryReady) {
        $primaryMeasurement = Measure-ProxyDownload -HostName $primaryHost -Port $primaryPort -Url $TestUrl -Count $Samples
    } else {
        $primaryMeasurement.Error = 'Primary proxy is not listening.'
    }
    if ($bulkReady) {
        $bulkMeasurement = Measure-ProxyDownload -HostName $bulkHost -Port $bulkPort -Url $TestUrl -Count $Samples
    } else {
        $bulkMeasurement.Error = 'Bulk proxy is not listening.'
    }
}

$multiplier = $null
if ($primaryMeasurement.MedianMbps -and $bulkMeasurement.MedianMbps) {
    $multiplier = [Math]::Round($bulkMeasurement.MedianMbps / $primaryMeasurement.MedianMbps, 2)
}

$result = [pscustomobject]@{
    SchemaVersion = 1
    CheckedAt = (Get-Date).ToString('o')
    PolicyState = [string]$policyState.State
    RoutePilotPolicyActive = [bool]$policyState.Active
    EdgePolicyDetail = [string]$policyState.Detail
    ConfigSource = [IO.Path]::GetFullPath($ConfigPath)
    TestUrl = if ($SkipBenchmark) { $null } else { $TestUrl }
    TestBytes = if ($SkipBenchmark) { $null } else { $TestBytes }
    SamplesRequested = if ($SkipBenchmark) { 0 } else { $Samples }
    Primary = [pscustomobject]@{
        Host = $primaryHost
        Port = $primaryPort
        Ready = $primaryReady
        MedianMbps = $primaryMeasurement.MedianMbps
        SamplesMbps = @($primaryMeasurement.Values)
        Error = $primaryMeasurement.Error
    }
    Bulk = [pscustomobject]@{
        Host = $bulkHost
        Port = $bulkPort
        Ready = $bulkReady
        MedianMbps = $bulkMeasurement.MedianMbps
        SamplesMbps = @($bulkMeasurement.Values)
        Error = $bulkMeasurement.Error
    }
    SpeedMultiplier = $multiplier
}

if ($AsJson) {
    $result | ConvertTo-Json -Depth 5
} else {
    $result
}
