[CmdletBinding()]
param(
    [string]$ConfigPath,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot

if (-not $ConfigPath) {
    $localConfig = Join-Path $projectRoot 'config\routepilot.local.json'
    $ConfigPath = if (Test-Path -LiteralPath $localConfig) {
        $localConfig
    } else {
        Join-Path $projectRoot 'config\routepilot.example.json'
    }
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $projectRoot 'runtime\routepilot.pac'
}

if (-not (Test-Path -LiteralPath $ConfigPath -PathType Leaf)) {
    throw "Configuration file not found: $ConfigPath"
}

$config = Get-Content -Raw -LiteralPath $ConfigPath | ConvertFrom-Json
if ([int]$config.schemaVersion -ne 1) {
    throw 'Unsupported or missing schemaVersion. Expected 1.'
}

function Get-ProxyDirective {
    param([Parameter(Mandatory)]$Proxy, [Parameter(Mandatory)][string]$Name)

    $hostName = ([string]$Proxy.host).Trim().ToLowerInvariant()
    if ($hostName -notin @('127.0.0.1', 'localhost')) {
        throw "$Name must use a loopback host (127.0.0.1 or localhost)."
    }
    $port = 0
    if (-not [int]::TryParse([string]$Proxy.port, [ref]$port) -or $port -lt 1 -or $port -gt 65535) {
        throw "$Name has an invalid TCP port."
    }
    return "PROXY ${hostName}:$port"
}

function Get-NormalizedDomains {
    param($Values, [Parameter(Mandatory)][string]$Name)

    $result = @()
    foreach ($value in @($Values)) {
        $domain = ([string]$value).Trim().TrimEnd('.').ToLowerInvariant()
        if (-not $domain -or $domain.Length -gt 253 -or $domain -notmatch '^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$' -or $domain.Contains('..')) {
            throw "$Name contains an invalid domain: $value"
        }
        $result += $domain
    }
    return @($result | Sort-Object -Unique)
}

$primaryDirective = Get-ProxyDirective -Proxy $config.primaryProxy -Name 'primaryProxy'
$bulkDirective = Get-ProxyDirective -Proxy $config.bulkProxy -Name 'bulkProxy'
$protectedDomains = Get-NormalizedDomains -Values $config.protectedDomains -Name 'protectedDomains'
$bulkDomains = Get-NormalizedDomains -Values $config.bulkDomains -Name 'bulkDomains'

if ($protectedDomains.Count -eq 0) { throw 'protectedDomains must contain at least one domain.' }
if ($bulkDomains.Count -eq 0) { throw 'bulkDomains must contain at least one domain.' }

$protectedSet = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
foreach ($domain in $protectedDomains) { [void]$protectedSet.Add($domain) }
foreach ($domain in $bulkDomains) {
    if ($protectedSet.Contains($domain)) {
        throw "A domain cannot be both protected and bulk: $domain"
    }
}

$protectedJson = ConvertTo-Json -InputObject ([object[]]$protectedDomains) -Compress
$bulkJson = ConvertTo-Json -InputObject ([object[]]$bulkDomains) -Compress
$defaultDirective = if ([bool]$config.defaultDirectFallback) {
    "$primaryDirective; DIRECT"
} else {
    $primaryDirective
}

$pac = @"
// Generated by RoutePilot. Edit the JSON configuration, not this file.
function FindProxyForURL(url, host) {
    host = host.toLowerCase();

    function isDomain(domain) {
        return host === domain || dnsDomainIs(host, "." + domain);
    }

    function inDomains(domains) {
        for (var i = 0; i < domains.length; i++) {
            if (isDomain(domains[i])) return true;
        }
        return false;
    }

    function isPrivateIPv4(value) {
        var parts = value.split(".");
        if (parts.length !== 4) return false;
        var numbers = [];
        for (var i = 0; i < 4; i++) {
            if (!/^\d+$/.test(parts[i])) return false;
            var number = parseInt(parts[i], 10);
            if (number < 0 || number > 255) return false;
            numbers.push(number);
        }
        return numbers[0] === 10 ||
            numbers[0] === 127 ||
            (numbers[0] === 192 && numbers[1] === 168) ||
            (numbers[0] === 172 && numbers[1] >= 16 && numbers[1] <= 31);
    }

    if (isPlainHostName(host) || host === "localhost" || isPrivateIPv4(host)) {
        return "DIRECT";
    }

    var protectedDomains = $protectedJson;
    if (inDomains(protectedDomains)) {
        // Fail closed: never add DIRECT or the bulk proxy here.
        return "$primaryDirective";
    }

    var bulkDomains = $bulkJson;
    if (inDomains(bulkDomains)) {
        return "$bulkDirective";
    }

    return "$defaultDirective";
}
"@

$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory) {
    New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}
Set-Content -LiteralPath $OutputPath -Value $pac -Encoding UTF8

[pscustomobject]@{
    OutputPath = [IO.Path]::GetFullPath($OutputPath)
    ProtectedDomains = $protectedDomains.Count
    BulkDomains = $bulkDomains.Count
    Primary = $primaryDirective
    Bulk = $bulkDirective
    DefaultDirectFallback = [bool]$config.defaultDirectFallback
} | ConvertTo-Json -Depth 3
